server:
  port: 10010

spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api  #添加路由
  routes:
    leyou-service: /item/**
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #熔断超时时间
ribbon:
  ConnectTimeout: 1000  #ribbon链接超时时间
  ReadTimeout: 3500  #ribbon读取超时时间
# MaxAutoRetries: 0  #当前服务重试次数
# MaxAutoRetriesNextServer: 0 #切换服务重试次数
