server:
  port: 10086

spring:
  application:
    name: leyou-register

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka



    #filter-only-up-instances: false    #表示是否要自己注册到自己的服务上
    #fetch-registry: false  #是否拉取服务

